DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." >/dev/null 2>&1 && pwd)"
PATH="$DIR/../src:$PATH"

ORIGINAL_RUNNER_DEBUG="$RUNNER_DEBUG"
ORIGINAL_GITHUB_ACTIONS="$GITHUB_ACTIONS"
ORIGINAL_GITHUB_ENV="$GITHUB_ENV"
ORIGINAL_GITHUB_OUTPUT="$GITHUB_OUTPUT"

function common_setup() {
	RUNNER_DEBUG=""
	GITHUB_ACTIONS=""
	GITHUB_ENV=$(mktemp)
	GITHUB_OUTPUT=$(mktemp)
}

function common_teardown() {
	rm -f "$GITHUB_ENV"
	rm -f "$GITHUB_OUTPUT"

	RUNNER_DEBUG="$ORIGINAL_RUNNER_DEBUG"
	GITHUB_ACTIONS="$ORIGINAL_GITHUB_ACTIONS"
	GITHUB_ENV="$ORIGINAL_GITHUB_ENV"
	GITHUB_OUTPUT="$ORIGINAL_GITHUB_OUTPUT"
}
